PATCH   http://localhost:3000/api/vehiculos/V001
Content-Type: application/json

{
    "foto": "https://carnovo.com/wp-content/uploads/2024/04/toyota-hilux-2024-2.jpg"
}

###
DELETE http://localhost:3000/api/vehiculos/V007